
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahwkysggmtcxxetcsjki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFod2t5c2dnbXRjeHhldGNzamtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjM5ODksImV4cCI6MjA2MzUzOTk4OX0.112lHt5iq5n-AvlJu0CWHGpZDG4hU3SYpmYs6QhIZ6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storage: localStorage
  }
});
